version: "3.8"

volumes:
  registry_data:

services:
  registry:
    image: registry:2
    restart: unless-stopped
    volumes:
      - registry_data:/var/lib/registry
      - ./config.yml:/etc/docker/registry/config.yml:ro
    networks:
      - cloudflare-net
    labels:
      - dockflare.enable=true
      - dockflare.hostname=registry.costic.dev
      - dockflare.service=http://registry:5000
      - dockflare.access.policy=bypass

networks:
  cloudflare-net:
    external: true
    name: cloudflare-net
