version: "3.8"
services:
  db:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    # Internal service only; no labels and no published ports.
    # Other stacks can connect via the Docker network alias "db"
    # if you later put them in a shared overlay/bridge.

volumes:
  pg_data:
