version: "3.8"

services:
  linkding:
    image: sissbruecker/linkding:latest
    restart: unless-stopped
    volumes:
      - linkding_data:/etc/linkding/data
    environment:
      # initial superuser (only created if it doesn't exist)
      - LD_SUPERUSER_NAME=${LD_SUPERUSER_NAME:-admin}
      - LD_SUPERUSER_PASSWORD=${LD_SUPERUSER_PASSWORD:-change-me}
      # helpful when behind Cloudflare reverse proxy
      - LD_CSRF_TRUSTED_ORIGINS=https://links.costic.dev
      - LD_LOG_X_FORWARDED_FOR=true
    networks:
      - cloudflare-net
    labels:
      - "dockflare.enable=true"
      - "dockflare.hostname=links.costic.dev"
      - "dockflare.service=http://linkding:9090"
      - "dockflare.access.policy=authenticate" # require login via CF Access

volumes:
  linkding_data:

networks:
  cloudflare-net:
    external: true
    name: cloudflare-net
