version: "3.8"

services:
  mouthful:
    image: vkuznecovas/mouthful:latest
    restart: unless-stopped
    user: "1000:1000" # drop root warning
    ports:
      - 8100:8080
    volumes:
      - /home/carter/infra/stacks/mouthful:/app/data   # must contain config.json
    networks:
      - cloudflare-net
    labels:
      - "dockflare.enable=true"
      - "dockflare.access.name=comments"
      - "dockflare.hostname=comments.costic.dev"
      - "dockflare.service=http://mouthful:8080" # dockflare doesn't care about host:container mapping
      - "dockflare.access.policy=bypass" # public comments

networks:
  cloudflare-net:
    external: true
    name: cloudflare-net
