version: "3.8"

services:
  mouthful:
    image: vkuznecovas/mouthful:latest
    restart: unless-stopped
    ports:
      - 8100:8080
    volumes:
      - ./config:/app/data   # must contain config.json
    networks:
      - cloudflare-net
    labels:
      - "dockflare.enable=true"
      - "dockflare.access.name=comments"
      - "dockflare.hostname=comments.costic.dev"
      - "dockflare.service=http://mouthful:8100"
      - "dockflare.access.policy=bypass" # public comments

networks:
  cloudflare-net:
    external: true
    name: cloudflare-net
