version: '3.8'

services:
  dockflare:
    image: alplat/dockflare:stable
    container_name: dockflare
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - STATE_FILE_PATH=/app/data/state.json
      - TZ=America/New_York
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - dockflare_data:/app/data
    networks:
      - cloudflare-net

volumes:
  dockflare_data:

networks:
  cloudflare-net:
    name: cloudflare-net